=== TheeAlex11/DAW1_25-26/lmsgi/ut04/ejerciciosPruebas/ejerciciosPruebasXML/ejerBiblioteca/biblioteca.dtd
<!-- Nodo principal -->
<!ELEMENT biblioteca (libro*, revistas*)>
<!-- Fin nodo -->

<!-- Inicio elementos y atributos de libro -->
<!ELEMENT libro (titulo, autor+, fecha-publicacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ATTLIST autor fecha-nacimiento CDATA #IMPLIED>
<!ELEMENT fecha-publicacion EMPTY>
<!ATTLIST fecha-publicacion año CDATA #REQUIRED>
<!-- Fin elementos y atributos de libro -->

=== TheeAlex11/DAW1_25-26/lmsgi/ut04/ejerciciosPruebas/ejerciciosPruebasXML/ejerBiblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Añadiendo los .dtd -->
<!-- <!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">  -->  <!-- De forma externa -->

<!DOCTYPE biblioteca [
    <!-- Nodo principal -->
    <!ELEMENT biblioteca (libro*, revistas*)>
    <!-- Fin nodo -->

    <!-- Inicio elementos y atributos de libro -->
    <!ELEMENT libro (titulo, autor+, fecha-publicacion)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ATTLIST autor fecha-nacimiento CDATA #IMPLIED>
    <!ELEMENT fecha-publicacion EMPTY>
    <!ATTLIST fecha-publicacion año CDATA #REQUIRED>
    <!-- Fin elementos y atributos de libro -->
]>

<!-- Fin añadiendo los .dtd -->
<biblioteca>
    <libro>
        <titulo>La vida está en otra parte</titulo>
        <autor>Milan Kundera</autor>
        <fecha-publicacion año="1973"></fecha-publicacion>
    </libro>
    <libro>
        <titulo>Pantaleón y las visitadoras</titulo>
        <autor fecha-nacimiento="28/03/1936">Mario Vargas Llosa</autor>
        <fecha-publicacion año="1973"></fecha-publicacion>
    </libro>
    <libro>
        <titulo>Conversación en la catedral</titulo>
        <autor fecha-nacimiento="28/03/1936">Mario Vargas Llosa</autor>
        <fecha-publicacion año="1969"></fecha-publicacion>
    </libro>
</biblioteca>
